services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ClaimabilityCheckerBundle\Command\ClaimabilityCheckCommand:
        tags:
            - { name: 'console.command' }
