services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ClaimabilityCheckerBundle\Service\CsvReader: ~

    ClaimabilityCheckerBundle\Chain\DeciderChain: ~
